// FILE: src/app/(protected)/report/page.tsx
"use client";

import { Fragment, useEffect, useMemo, useState } from "react";
import { AppShell } from "@/components/app-shell";
import {
  FileText,
  RefreshCw,
  Download,
  X,
  ChevronDown,
  MapPin,
  Zap,
  ExternalLink,
  RotateCcw,
  FileIcon,
  Eye,
} from "lucide-react";

type ReportListItem = {
  id: string;
  createdAt: string; // ISO
  commodity: string;
  region: string;
  fileName: string;

  source: "incoming" | "archive";
  active: boolean;

  objectName: string;      // incoming/... or archive/...
  cleanObjectName: string; // clean/...json
  hasClean: boolean;
  generatedBy: string;     // "system" or email
};

function cx(...classes: Array<string | false | null | undefined>) {
  return classes.filter(Boolean).join(" ");
}

export default function ReportsPage() {
  // Filter states
  const [fromDate, setFromDate] = useState<string>("");
  const [toDate, setToDate] = useState<string>("");
  const [statusFilter, setStatusFilter] = useState<"all" | "active" | "archived">("all");
  const [generatedBy, setGeneratedBy] = useState<string>("all");

  // Data states
  const [items, setItems] = useState<ReportListItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [loadErr, setLoadErr] = useState<string | null>(null);

  // Expandable rows
  const [expandedRows, setExpandedRows] = useState<Set<string>>(new Set());

  // Viewer modal state
  const [viewOpen, setViewOpen] = useState(false);
  const [viewLoading, setViewLoading] = useState(false);
  const [viewErr, setViewErr] = useState<string | null>(null);
  const [selected, setSelected] = useState<ReportListItem | null>(null);
  const [viewJson, setViewJson] = useState<any | null>(null);

  async function openGeneratedReport(it: ReportListItem) {
    if (!it.hasClean) return;

    setSelected(it);
    setViewOpen(true);
    setViewLoading(true);
    setViewErr(null);
    setViewJson(null);

    try {
      const res = await fetch(
        `/api/report/read?objectName=${encodeURIComponent(it.cleanObjectName)}`,
        { cache: "no-store" }
      );

      const txt = await res.text().catch(() => "");
      let data: any;

      try {
        data = txt ? JSON.parse(txt) : null;
      } catch {
        throw new Error(`Non-JSON response (${res.status}): ${txt.slice(0, 160)}`);
      }

      if (!res.ok || data?.ok === false) {
        throw new Error(data?.error ?? `Read failed (${res.status})`);
      }

      setViewJson(
        data.kind === "json"
          ? data.json
          : { kind: data.kind, text: data.text }
      );
    } catch (e: any) {
      setViewErr(e?.message ?? "Failed to load generated report");
    } finally {
      setViewLoading(false);
    }
  }

  async function refresh() {
    setLoading(true);
    setLoadErr(null);
    try {
      const res = await fetch("/api/report/list", { cache: "no-store" });
      const data = await res.json();
      if (!res.ok || !data?.ok) throw new Error(data?.error ?? `List failed (${res.status})`);
      setItems(Array.isArray(data.items) ? data.items : []);
    } catch (e: any) {
      setLoadErr(e?.message ?? "Failed to load");
      setItems([]);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    refresh();
  }, []);

  // Filtered rows
  const rows = useMemo(() => {
    const fromTs =
      fromDate && /^\d{4}-\d{2}-\d{2}$/.test(fromDate)
        ? new Date(fromDate + "T00:00:00").getTime()
        : null;

    const toTs =
      toDate && /^\d{4}-\d{2}-\d{2}$/.test(toDate)
        ? new Date(toDate + "T23:59:59").getTime()
        : null;

    return items.filter((it) => {
      // Status filter
      const isActive = Boolean(it.active);
      const okStatus =
        statusFilter === "all" ||
        (statusFilter === "active" && isActive) ||
        (statusFilter === "archived" && !isActive);

      // Date filter
      const createdTs =
        typeof it.createdAt === "number" ? it.createdAt : new Date(String(it.createdAt ?? "")).getTime();

      const okFromDate = fromTs == null || (Number.isFinite(createdTs) && createdTs >= fromTs);
      const okToDate = toTs == null || (Number.isFinite(createdTs) && createdTs <= toTs);

      // Generated by filter
      const okGeneratedBy =
        generatedBy === "all" ||
        (generatedBy === "system" && it.generatedBy === "system") ||
        (generatedBy === "team" && it.generatedBy !== "system");

      return okStatus && okFromDate && okToDate && okGeneratedBy;
    });
  }, [items, statusFilter, fromDate, toDate, generatedBy]);

  function toggleRow(id: string) {
    setExpandedRows((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
  }

  function resetFilters() {
    setFromDate("");
    setToDate("");
    setStatusFilter("all");
    setGeneratedBy("all");
  }

  async function openSigned(objectName: string) {
    const res = await fetch(`/api/files/signedread?objectName=${encodeURIComponent(objectName)}`, {
      cache: "no-store",
    });
    const data = await res.json();
    if (!res.ok || !data?.ok || !data?.url) throw new Error(data?.error ?? "Signed URL failed");
    window.open(data.url, "_blank", "noopener,noreferrer");
  }

  return (
    <AppShell title="Reports">
      <div className="workspace">
        {/* LEFT: Filters sidebar */}
        <aside className="control-sidebar">
          <div className="module">
            <div className="module-header">Filters</div>
            <div className="module-content">
              {/* Forecast Date */}
              <div className="input-row">
                <label className="input-label">Forecast Date</label>
                <div style={{ display: "flex", flexDirection: "column", gap: "0.5rem" }}>
                  <div>
                    <span style={{ fontSize: "0.75rem", color: "#7a869a", marginBottom: "0.25rem", display: "block" }}>From</span>
                    <input
                      className="tt-input"
                      type="date"
                      value={fromDate}
                      onChange={(e) => setFromDate(e.target.value)}
                    />
                  </div>
                  <div>
                    <span style={{ fontSize: "0.75rem", color: "#7a869a", marginBottom: "0.25rem", display: "block" }}>To</span>
                    <input
                      className="tt-input"
                      type="date"
                      value={toDate}
                      onChange={(e) => setToDate(e.target.value)}
                    />
                  </div>
                </div>
              </div>

              {/* Status */}
              <div className="input-row">
                <label className="input-label">Status</label>
                <select
                  className="tt-select"
                  value={statusFilter}
                  onChange={(e) => setStatusFilter(e.target.value as any)}
                >
                  <option value="all">All</option>
                  <option value="active">Active</option>
                  <option value="archived">Archived</option>
                </select>
              </div>

              {/* Generated By */}
              <div className="input-row">
                <label className="input-label">Generated By</label>
                <select
                  className="tt-select"
                  value={generatedBy}
                  onChange={(e) => setGeneratedBy(e.target.value)}
                >
                  <option value="all">All</option>
                  <option value="team">Team members</option>
                  <option value="system">System</option>
                </select>
              </div>

              {/* Filter Buttons */}
              <div className="filter-buttons">
                <button className="filter-btn-primary" type="button" onClick={refresh} disabled={loading}>
                  APPLY FILTERS
                </button>
                <button className="filter-btn-secondary" type="button" onClick={resetFilters}>
                  <RotateCcw className="h-3 w-3" />
                  RESET
                </button>
              </div>

              {loadErr && (
                <div style={{ marginTop: 10, color: "#de350b", fontWeight: 700, fontSize: 13 }}>
                  {loadErr}
                </div>
              )}
            </div>
          </div>
        </aside>

        {/* RIGHT: Main panel */}
        <main className="main-panel">
          <section className="panel-section">
            {/* Header */}
            <div className="section-header">
              <h2 className="section-title">REPORT FILES</h2>
              <div className="section-actions">
                <button className="toolbar-btn" type="button" onClick={refresh} disabled={loading}>
                  <RefreshCw className="h-4 w-4" />
                  Refresh
                </button>
              </div>
            </div>

            {/* Info Banner */}
            <div className="report-info-banner">
              <p className="report-info-text">
                Reports are used for audit and review of forecast assumptions, extracted signals, and bid recommendations.
                Forecast integrity depends on having complete report records.
              </p>
              <div className="report-links">
                <a href="#" className="report-link">
                  VIEW REQUIREMENTS
                </a>
                <a href="#" className="report-link">
                  <ExternalLink className="h-3 w-3" />
                  FIND ALL RESULTS &gt;
                </a>
              </div>
            </div>

            {/* Inner Section Header */}
            <div className="section-header" style={{ background: "var(--tt-bg-primary)", borderBottom: "1px solid var(--tt-border)" }}>
              <h3 style={{ fontSize: "1rem", fontWeight: 700, margin: 0 }}>REPORT FILES</h3>
              <div className="section-actions">
                <button className="toolbar-btn" type="button" onClick={refresh} disabled={loading}>
                  <RefreshCw className="h-4 w-4" />
                  Refresh
                </button>
              </div>
            </div>

            {/* Table */}
            <div className="tt-uploadTableWrap">
              <table className="report-table">
                <thead>
                  <tr>
                    <th style={{ width: 40 }}></th>
                    <th>Date</th>
                    <th>File Name</th>
                    <th>Type</th>
                    <th>Coverage</th>
                    <th>Forecast</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  {rows.length ? (
                    rows.map((it) => {
                      const isExpanded = expandedRows.has(it.id);

                      return (
                        <Fragment key={it.id}>
                          {/* Parent Row */}
                          <tr
                            className={cx("report-row", isExpanded && "report-row-expanded")}
                            onClick={() => toggleRow(it.id)}
                          >
                            <td>
                              <ChevronDown
                                className={cx("report-expand-icon", isExpanded && "report-expand-icon-open")}
                              />
                            </td>
                            <td>{formatDate(it.createdAt)}</td>
                            <td style={{ fontWeight: 600 }}>{it.fileName}</td>
                            <td>
                              {it.active && it.hasClean ? (
                                <span className="report-type-badge">
                                  <Zap className="h-3 w-3" />
                                  SET IN LATEST FORECAST
                                </span>
                              ) : !it.active ? (
                                <span className="report-badge report-badge-deprecated">
                                  DEPRECATED
                                </span>
                              ) : null}
                            </td>
                            <td></td>
                            <td></td>
                            <td onClick={(e) => e.stopPropagation()}>
                              <div className="report-actions">
                                {it.active && it.hasClean ? (
                                  <button
                                    className="report-action-btn"
                                    type="button"
                                    onClick={() => openGeneratedReport(it)}
                                  >
                                    <Eye className="h-4 w-4" />
                                    <span>View Forecast Report</span>
                                  </button>
                                ) : !it.active ? (
                                  <button
                                    className="report-action-btn"
                                    type="button"
                                    onClick={() => openSigned(it.objectName)}
                                  >
                                    <FileIcon className="h-4 w-4" />
                                    <span>View Superseded Report</span>
                                  </button>
                                ) : null}
                                <button
                                  className="report-action-icon"
                                  type="button"
                                  onClick={() => openSigned(it.objectName)}
                                  title="Download"
                                >
                                  <Download className="h-4 w-4" />
                                </button>
                              </div>
                            </td>
                          </tr>

                          {/* Expanded Detail Panel */}
                          {isExpanded && (
                            <tr key={`${it.id}-detail`}>
                              <td colSpan={7} style={{ padding: 0 }}>
                                <div className="report-detail-panel">
                                  {/* Forecast Badge */}
                                  {it.active && (
                                    <div className="report-forecast-badge">
                                      <Zap className="h-3 w-3" />
                                      Used in Latest Forecast
                                      <ChevronDown className="h-3 w-3" />
                                    </div>
                                  )}

                                  {/* Signal Card */}
                                  <div className="report-signal-card">
                                    <div className="report-signal-header">
                                      <FileText className="report-signal-icon" />
                                      <div>
                                        <h4 className="report-signal-title">
                                          Market Signal Summary - {it.region || "All Regions"} - {formatYearMonth(it.createdAt)}
                                        </h4>
                                        <div className="report-signal-meta">
                                          <span className={cx("report-badge", it.active ? "report-badge-active" : "report-badge-archived")}>
                                            {it.active ? "ACTIVE" : "ARCHIVED"}
                                          </span>
                                          <span className="report-signal-location">
                                            <MapPin className="h-3 w-3" />
                                            {it.commodity}, {formatDateRange(it.createdAt)}
                                          </span>
                                          <span className="report-signal-stats">
                                            <Zap className="h-3 w-3" />
                                            {it.hasClean ? "7 Signals (3 Supply, 2 Demand, 2 Policy)" : "No signals extracted"}
                                          </span>
                                        </div>
                                      </div>
                                    </div>

                                    <div className="report-signal-footer">
                                      <div className="report-signal-generator">
                                        <span>Generated {formatRelativeTime(it.createdAt)} by</span>
                                        <a href="#">{it.generatedBy}</a>
                                        <span>|</span>
                                        <span>Model v5.12</span>
                                        <span>|</span>
                                        <span>{it.hasClean ? "7 Signals extracted" : "Processing"}</span>
                                      </div>
                                      <button
                                        className="report-download-link"
                                        type="button"
                                        onClick={() => openSigned(it.objectName)}
                                      >
                                        <Download className="h-4 w-4" />
                                        DOWNLOAD
                                      </button>
                                    </div>
                                  </div>
                                </div>
                              </td>
                            </tr>
                          )}
                        </Fragment>
                      );
                    })
                  ) : (
                    <tr>
                      <td colSpan={7} style={{ padding: "1.25rem", color: "#7a869a" }}>
                        {loading ? "Loading..." : "No reports match your filters."}
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>

            {/* Footer Notice */}
            <div className="report-footer-notice">
              Reports are retained for 1 year, older data is automatically purged.
            </div>
          </section>

          {/* Viewer popup */}
          {viewOpen && (
            <div className="fixed inset-0 z-[13000]">
              <div
                className="absolute inset-0"
                style={{ background: "rgba(9,30,66,0.35)" }}
                onClick={() => setViewOpen(false)}
                aria-hidden="true"
              />
              <div className="absolute inset-0 flex items-center justify-center p-4">
                <div style={{ width: "100%", maxWidth: 980, background: "#fff", border: "1px solid #dfe1e6" }}>
                  <div style={{ padding: "14px 16px", background: "#e9ecef", borderBottom: "1px solid #dfe1e6" }}>
                    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12 }}>
                      <div>
                        <div style={{ fontWeight: 900, letterSpacing: 0.3 }}>GENERATED REPORT</div>
                      </div>
                      <button
                        className="toolbar-btn"
                        type="button"
                        onClick={() => setViewOpen(false)}
                        title="Close"
                      >
                        <X className="h-4 w-4" />
                        Close
                      </button>
                    </div>
                  </div>

                  <div style={{ padding: 12 }}>
                    {viewErr ? (
                      <div style={{ padding: 12, border: "1px solid #dfe1e6", background: "#ffebe6", color: "#de350b", fontWeight: 700 }}>
                        {viewErr}
                      </div>
                    ) : viewLoading ? (
                      <div style={{ padding: 12, color: "#7a869a" }}>Loading…</div>
                    ) : (
                      <iframe
                        title="Report viewer"
                        src={`/report/view?objectName=${encodeURIComponent(selected?.cleanObjectName ?? "")}`}
                        className="h-[72vh] w-full"
                        style={{ border: "1px solid #dfe1e6" }}
                      />
                    )}
                  </div>

                  <div style={{ padding: 12, background: "#f8f9fa", borderTop: "1px solid #dfe1e6", display: "flex", justifyContent: "flex-end" }}>
                    <button className="toolbar-btn" type="button" onClick={() => setViewOpen(false)}>
                      Close
                    </button>
                  </div>
                </div>
              </div>
            </div>
          )}
        </main>
      </div>
    </AppShell>
  );
}

// Helper functions
const DATE_FMT = new Intl.DateTimeFormat("en-AU", {
  year: "numeric",
  month: "short",
  day: "2-digit",
  timeZone: "Australia/Sydney",
});

function formatDate(iso: string) {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return "-";
  return DATE_FMT.format(d);
}

function formatYearMonth(iso: string) {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return "-";
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, "0");
  return `${year}${month}`;
}

function formatDateRange(iso: string) {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return "-";
  const month = d.toLocaleString("en-AU", { month: "short", timeZone: "Australia/Sydney" });
  const year = d.getFullYear();
  const startDay = "01";
  const endDay = new Date(year, d.getMonth() + 1, 0).getDate();
  return `${startDay} ${month} – ${endDay} ${month} ${year}`;
}

function formatRelativeTime(iso: string) {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return "-";
  const now = Date.now();
  const diff = now - d.getTime();
  const hours = Math.floor(diff / (1000 * 60 * 60));
  const days = Math.floor(hours / 24);

  if (days > 0) return `${days} day${days > 1 ? "s" : ""} ago`;
  if (hours > 0) return `${hours} hour${hours > 1 ? "s" : ""} ago`;
  return "just now";
}
